export const products = [
    {
      id: 1,
      name: "Gradient Graphic T-shirt",
      price: 145,
      rating: 3.5,
      maxRating: 5,
      image: "https://image1.superdry.com/static/images/optimised/zoom/upload9223368955665648599.jpg",
      color: "white",
      sizes: ["S", "M", "L", "XL"],
    },
    {
      id: 2,
      name: "Polo with Tipping Details",
      price: 180,
      rating: 4.5,
      maxRating: 5,
      image: "https://image1.superdry.com/static/images/optimised/zoom/upload9223368955665648599.jpg",
      color: "red",
      sizes: ["M", "L", "XL"],
    },
    {
      id: 3,
      name: "Black Striped T-shirt",
      price: 120,
      originalPrice: 150,
      discount: 20,
      rating: 5.0,
      maxRating: 5,
      image: "https://image1.superdry.com/static/images/optimised/zoom/upload9223368955665648599.jpg",
      color: "black",
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 4,
      name: "Skinny Fit Jeans",
      price: 240,
      originalPrice: 260,
      discount: 20,
      rating: 3.5,
      maxRating: 5,
      image: "https://image1.superdry.com/static/images/optimised/zoom/upload9223368955665648599.jpg",
      color: "blue",
      sizes: ["S", "M", "L"],
    },
    {
      id: 5,
      name: "Checkered Shirt",
      price: 180,
      rating: 4.5,
      maxRating: 5,
      image: "https://image1.superdry.com/static/images/optimised/zoom/upload9223368955665648599.jpg",
      color: "red",
      sizes: ["M", "L", "XL", "XXL"],
    },
    {
      id: 6,
      name: "Sleeve Striped T-shirt",
      price: 130,
      originalPrice: 160,
      discount: 20,
      rating: 4.5,
      maxRating: 5,
      image: "https://image1.superdry.com/static/images/optimised/zoom/upload9223368955665648599.jpg",
      color: "orange",
      sizes: ["XS", "S", "M"],
    },
    {
      id: 7,
      name: "Vertical Striped Shirt",
      price: 212,
      originalPrice: 232,
      discount: 20,
      rating: 5.0,
      maxRating: 5,
      image: "https://image1.superdry.com/static/images/optimised/zoom/upload9223368955665648599.jpg",
      color: "green",
      sizes: ["M", "L", "XL"],
    },
    {
      id: 8,
      name: "Courage Graphic T-shirt",
      price: 145,
      rating: 4.0,
      maxRating: 5,
      image: "https://image1.superdry.com/static/images/optimised/zoom/upload9223368955665648599.jpg",
      color: "orange",
      sizes: ["S", "M", "L"],
    },
    {
      id: 9,
      name: "Loose Fit Bermuda Shorts",
      price: 80,
      rating: 3.0,
      maxRating: 5,
      image: "https://image1.superdry.com/static/images/optimised/zoom/upload9223368955665648599.jpg",
      color: "blue",
      sizes: ["M", "L", "XL"],
    },

  ]
  
  export type Product = (typeof products)[0]
  
  export const COLORS = [
    { name: "green", value: "bg-green-500" },
    { name: "red", value: "bg-red-500" },
    { name: "yellow", value: "bg-yellow-400" },
    { name: "orange", value: "bg-orange-500" },
    { name: "cyan", value: "bg-cyan-400" },
    { name: "blue", value: "bg-blue-600" },
    { name: "purple", value: "bg-purple-600" },
    { name: "pink", value: "bg-pink-500" },
    { name: "white", value: "bg-white border" },
    { name: "black", value: "bg-black" },
  ]
  
  export const SIZES = [
    { label: "XX-Small", value: "XXS" },
    { label: "X-Small", value: "XS" },
    { label: "Small", value: "S" },
    { label: "Medium", value: "M" },
    { label: "Large", value: "L" },
    { label: "X-Large", value: "XL" },
    { label: "XX-Large", value: "XXL" },
    { label: "3X-Large", value: "3XL" },
    { label: "4X-Large", value: "4XL" },
  ]
  
  